[package]
name = "ztnet"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive", "env"] }
clap_complete = "4.5"
directories = "6.0"
humantime = "2.2"
serde = { version = "1.0", features = ["derive"] }
thiserror = "2.0"
toml = "0.9"
